version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: equipment_inventory_db
      POSTGRES_USER: equipment_user
      POSTGRES_PASSWORD: ronaldo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=equipment_inventory_db
      - DATABASE_USER=equipment_user
      - DATABASE_PASSWORD=ronaldo
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
